### ISSUE TITLE
I can't run the composer

### ISSUE THREAD

**Issue by hieuhuynh93** [fabian-tomischka/php-avatar-generator#1]
Hi,
I can't run the composer, it got the error.
Please help me check it
![ExJd.png](https://i.snapgo.top/ExJd.png)

Thank you.

**Comment by pluc** [comment]
@hieuhuynh93 Use this:

`composer require fabian-tomischka/php-avatar-generator:dev-master`

**Comment by hieuhuynh93** [comment]
> @hieuhuynh93 Use this:
> 
> `composer require fabian-tomischka/php-avatar-generator:dev-master`

Thank you. But I didn't use this one. I'm using CSS to do this feature.
